### ISSUE TITLE
在react native 0.47的项目中运行报错 

### ISSUE THREAD

**Issue by CodeLYQ** [SpadeGod/react-native-aliyun-oss#3]
错误提示是这个方法报错，在0.47版本中Deprecated了。
 // Deprecated RN 0.47
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

希望有空改一下。
BTW，谢谢。

**Comment by SpadeGod** [comment]
the bug is fixed. Duplicate of #4
