### ISSUE TITLE
RN 0.51 安装报错

### ISSUE THREAD

**Issue by 1c7** [SpadeGod/react-native-aliyun-oss#9]
## 过程
```
npm install --save react-native-aliyun-oss-cp
react-native link
react-native run-android
```
获得如下结果
![image](https://user-images.githubusercontent.com/1804755/34199488-e84efdb2-e5a8-11e7-812c-3c75ddedb59a.png)

## 环境 React Native 0.51 + macOS
![image](https://user-images.githubusercontent.com/1804755/34199510-f8026596-e5a8-11e7-9b7b-d8f188aa8c00.png)
![image](https://user-images.githubusercontent.com/1804755/34199620-51a6bde0-e5a9-11e7-982d-7081eec1e9ce.png)

## 问题
如何修复这个问题？如何成功安装并使用？
如果你需要更多环境信息，请告知，我会立刻提供。

## 我想实现的最终结果
React Native 上传文件到阿里云 OSS 上。

非常感谢 :D

**Comment by mengerpiao** [comment]
他这个很老了，是0.39版本之前的了，你需要修改成import <framework>形式

**Comment by 1c7** [comment]
@mengerpiao 嗯这样。感谢回复~
（我这个问题是2017年12月提的，后来自己解决了，没用 import
